### ISSUE TITLE
api changes and rebranding

### ISSUE THREAD

**Issue by NikkyAI** [matthewdias/hummingbird_list#1]
https://forums.hummingbird.me/t/kitsu-api-documentation/33367

i will try my best to make it work and then eventually push that too github,
but you should be aware

**Comment by NikkyAI** [comment]
the hummingbird api is gone

**Comment by matthewdias** [comment]
I'm aware, but thanks for the notice. (That's actually my forum post lol). I've been using sonarr for awhile instead of flexget, but might come back and see how it is because contributing to sonarr is not a fun time 😅

**Comment by NikkyAI** [comment]
right.. i am blind.. how could i not see the name..
btw here is a working kitsu.io plugin
https://gist.github.com/NikkyAI/b0f8249bed7fee0af667e31b5c745157
i will put that on my github soon and PR to flexget etc once i am convinced its solid (and they rolled out the v17 namespace)

**Comment by matthewdias** [comment]
@NikkyAI cool. be advised, v17 probably won't be out for a long time, but i don't think the library api will have any breaking changes before then. also, consider using authentication, because logged out requests to `/library-entries` won't include private entries.

**Comment by NikkyAI** [comment]
i will add t to the existing PR once there is more info about oauth in the docs and i can figure out how to use it in requests

**Comment by NikkyAI** [comment]
you could mention it here https://github.com/Flexget/Flexget/pull/1583

**Comment by NikkyAI** [comment]
https://flexget.com/Plugins/kitsu will be in the next release of flexget, it is loosely based on this plugin
